/* The following code was generated by JFlex 1.4.3 on 29/05/22 11:03 PM */

/* PAQUETE Y LIBRERIAS A UTILIZAR*/
package proyectocompiladores;

import static proyectocompiladores.Tokens.*;

/* DECLARACIONES A UTILIZAR*/

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 29/05/22 11:03 PM from the specification file
 * <tt>C:/Users/KAZZU/OneDrive/Documents/NetBeansProjects/ProyectoCompiladores/src/proyectocompiladores/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\61\2\0\1\3\22\0\1\3\1\46\1\54\1\60"+
    "\1\53\1\52\1\56\1\0\1\42\1\43\1\50\1\52\1\3\1\47"+
    "\1\0\1\51\12\2\1\0\1\55\1\44\1\45\1\44\2\0\4\1"+
    "\1\10\12\1\1\12\2\1\1\4\1\11\1\14\5\1\1\36\1\0"+
    "\1\37\1\0\1\1\1\0\1\21\1\20\1\23\1\31\1\5\1\27"+
    "\1\34\1\33\1\26\1\1\1\22\1\30\1\35\1\25\1\24\1\15"+
    "\1\1\1\17\1\7\1\6\1\13\1\1\1\32\1\16\2\1\1\40"+
    "\1\57\1\41\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\14\2\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\3\16"+
    "\1\17\1\20\1\21\3\15\14\2\1\22\2\2\1\23"+
    "\2\2\1\0\1\13\1\24\1\25\1\4\1\26\10\2"+
    "\1\27\1\30\3\2\1\0\1\2\1\31\5\2\1\32"+
    "\1\3\4\2\1\33\1\34\1\35\3\2\1\36";

  private static int [] zzUnpackAction() {
    int [] result = new int[93];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\62\0\144\0\226\0\310\0\372\0\u012c\0\u015e"+
    "\0\u0190\0\u01c2\0\u01f4\0\u0226\0\u0258\0\u028a\0\u02bc\0\u02ee"+
    "\0\u0320\0\62\0\62\0\62\0\62\0\u0352\0\62\0\u0384"+
    "\0\u0384\0\u0384\0\u03b6\0\u03e8\0\u041a\0\62\0\62\0\62"+
    "\0\u044c\0\u047e\0\62\0\u04b0\0\u04e2\0\u0514\0\u0546\0\u0578"+
    "\0\u05aa\0\u05dc\0\u060e\0\u0640\0\u0672\0\u06a4\0\u06d6\0\144"+
    "\0\u0708\0\u073a\0\144\0\u076c\0\u079e\0\u07d0\0\62\0\62"+
    "\0\62\0\u0802\0\144\0\u0834\0\u0866\0\u0898\0\u08ca\0\u08fc"+
    "\0\u092e\0\u0960\0\u0992\0\144\0\144\0\u09c4\0\u09f6\0\u0a28"+
    "\0\u0a5a\0\u0a8c\0\144\0\u0abe\0\u0af0\0\u0b22\0\u0b54\0\u0b86"+
    "\0\144\0\62\0\u0bb8\0\u0bea\0\u0c1c\0\u0c4e\0\144\0\144"+
    "\0\144\0\u0c80\0\u0cb2\0\u0ce4\0\144";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[93];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\3\1\10"+
    "\2\3\1\11\2\3\1\12\2\3\1\13\2\3\1\14"+
    "\2\3\1\15\1\16\1\3\1\17\1\20\2\3\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\33\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\5\63\0\2\3\1\0\32\3"+
    "\26\0\1\4\62\0\1\5\55\0\1\5\1\0\2\3"+
    "\1\0\1\3\1\44\1\45\1\3\1\46\25\3\25\0"+
    "\2\3\1\0\12\3\1\47\11\3\1\50\5\3\25\0"+
    "\2\3\1\0\1\3\1\44\24\3\1\51\3\3\25\0"+
    "\2\3\1\0\7\3\1\52\1\53\21\3\25\0\2\3"+
    "\1\0\7\3\1\54\22\3\25\0\2\3\1\0\13\3"+
    "\1\55\16\3\25\0\2\3\1\0\20\3\1\56\11\3"+
    "\25\0\2\3\1\0\21\3\1\57\1\3\1\60\6\3"+
    "\25\0\2\3\1\0\20\3\1\61\11\3\25\0\2\3"+
    "\1\0\1\3\1\62\16\3\1\63\11\3\25\0\2\3"+
    "\1\0\27\3\1\64\2\3\25\0\2\3\1\0\15\3"+
    "\1\65\14\3\73\0\1\66\57\0\1\67\61\0\1\70"+
    "\61\0\1\70\2\0\1\71\56\0\1\70\3\0\1\72"+
    "\66\0\1\43\62\0\1\43\3\0\2\3\1\0\2\3"+
    "\1\73\27\3\25\0\2\3\1\0\13\3\1\74\16\3"+
    "\25\0\2\3\1\0\5\3\1\73\24\3\25\0\2\3"+
    "\1\0\11\3\1\75\20\3\25\0\2\3\1\0\3\3"+
    "\1\76\26\3\25\0\2\3\1\0\22\3\1\77\7\3"+
    "\25\0\2\3\1\0\2\3\1\100\27\3\25\0\2\3"+
    "\1\0\5\3\1\100\24\3\25\0\2\3\1\0\2\3"+
    "\1\101\27\3\25\0\2\3\1\0\1\3\1\102\30\3"+
    "\25\0\2\3\1\0\21\3\1\103\10\3\25\0\2\3"+
    "\1\0\2\3\1\104\27\3\25\0\2\3\1\0\13\3"+
    "\1\105\16\3\25\0\2\3\1\0\23\3\1\106\6\3"+
    "\25\0\2\3\1\0\22\3\1\107\7\3\25\0\2\3"+
    "\1\0\22\3\1\110\7\3\26\0\1\111\57\0\61\72"+
    "\2\0\2\3\1\0\22\3\1\112\7\3\25\0\2\3"+
    "\1\0\13\3\1\73\16\3\25\0\2\3\1\0\1\3"+
    "\1\113\30\3\25\0\2\3\1\0\2\3\1\114\27\3"+
    "\25\0\2\3\1\0\1\73\31\3\25\0\2\3\1\0"+
    "\3\3\1\73\26\3\25\0\2\3\1\0\15\3\1\115"+
    "\14\3\25\0\2\3\1\0\2\3\1\116\27\3\25\0"+
    "\2\3\1\0\15\3\1\117\14\3\25\0\2\3\1\0"+
    "\24\3\1\120\5\3\25\0\2\3\1\0\21\3\1\121"+
    "\10\3\26\0\1\111\40\0\1\122\17\0\2\3\1\0"+
    "\21\3\1\123\10\3\25\0\2\3\1\0\17\3\1\124"+
    "\12\3\25\0\2\3\1\0\16\3\1\73\13\3\25\0"+
    "\2\3\1\0\22\3\1\125\7\3\25\0\2\3\1\0"+
    "\7\3\1\126\22\3\25\0\2\3\1\0\1\3\1\127"+
    "\30\3\25\0\2\3\1\0\30\3\1\130\1\3\25\0"+
    "\2\3\1\0\27\3\1\131\2\3\25\0\2\3\1\0"+
    "\21\3\1\132\10\3\25\0\2\3\1\0\24\3\1\133"+
    "\5\3\25\0\2\3\1\0\7\3\1\134\22\3\25\0"+
    "\2\3\1\0\2\3\1\135\27\3\25\0\2\3\1\0"+
    "\1\3\1\73\30\3\24\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3350];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\17\1\4\11\1\1\1\11\6\1\3\11"+
    "\2\1\1\11\22\1\1\0\3\11\17\1\1\0\10\1"+
    "\1\11\13\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[93];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 146) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 16: 
          { lexeme=yytext(); return Comillas;
          }
        case 31: break;
        case 22: 
          { lexeme=yytext(); return PalabraReservada;
          }
        case 32: break;
        case 17: 
          { lexeme=yytext(); return PuntoComa;
          }
        case 33: break;
        case 10: 
          { lexeme=yytext(); return ParentesisCierre;
          }
        case 34: break;
        case 28: 
          { lexeme=yytext(); return Cadena;
          }
        case 35: break;
        case 13: 
          { lexeme=yytext(); return OperadoresLogicos;
          }
        case 36: break;
        case 23: 
          { lexeme=yytext(); return Int;
          }
        case 37: break;
        case 8: 
          { lexeme=yytext(); return LlaveCierre;
          }
        case 38: break;
        case 30: 
          { lexeme=yytext(); return Defecto;
          }
        case 39: break;
        case 6: 
          { lexeme = yytext(); return CorcheteCierre;
          }
        case 40: break;
        case 18: 
          { lexeme=yytext(); return If;
          }
        case 41: break;
        case 15: 
          { lexeme=yytext(); return Dolar;
          }
        case 42: break;
        case 12: 
          { lexeme=yytext(); return Igual;
          }
        case 43: break;
        case 29: 
          { lexeme=yytext(); return SwitchCase;
          }
        case 44: break;
        case 3: 
          { lexeme=yytext(); return Numero;
          }
        case 45: break;
        case 24: 
          { lexeme=yytext(); return For;
          }
        case 46: break;
        case 9: 
          { lexeme=yytext(); return ParentesisApertura;
          }
        case 47: break;
        case 2: 
          { lexeme=yytext(); return Identificador;
          }
        case 48: break;
        case 21: 
          { lexeme=yytext(); return Exponente;
          }
        case 49: break;
        case 19: 
          { lexeme=yytext(); return Do;
          }
        case 50: break;
        case 1: 
          { return ERROR;
          }
        case 51: break;
        case 26: 
          { lexeme=yytext(); return Main;
          }
        case 52: break;
        case 4: 
          { /*Ignore*/
          }
        case 53: break;
        case 14: 
          { lexeme = yytext(); return OperadoresAritmeticos;
          }
        case 54: break;
        case 7: 
          { lexeme=yytext(); return LlaveApertura;
          }
        case 55: break;
        case 20: 
          { lexeme = yytext(); return OperadoresAtribucion;
          }
        case 56: break;
        case 5: 
          { lexeme = yytext(); return CorcheteApertura;
          }
        case 57: break;
        case 27: 
          { lexeme=yytext(); return While;
          }
        case 58: break;
        case 11: 
          { lexeme = yytext(); return OperadoresRelacionales;
          }
        case 59: break;
        case 25: 
          { lexeme=yytext(); return Else;
          }
        case 60: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
