
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun May 29 23:03:39 CST 2022
//----------------------------------------------------

package proyectocompiladores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PuntoComa = 30;
  public static final int Exponente = 32;
  public static final int If = 6;
  public static final int CorcheteCierre = 28;
  public static final int CorcheteApertura = 27;
  public static final int Else = 7;
  public static final int LlaveCierre = 26;
  public static final int PalabraReservada = 12;
  public static final int OperadoresAritmeticos = 15;
  public static final int Defecto = 14;
  public static final int OperadoresLogicos = 16;
  public static final int ParentesisCierre = 24;
  public static final int OperadoresBooleano = 22;
  public static final int While = 9;
  public static final int Int = 4;
  public static final int Cadena = 5;
  public static final int For = 10;
  public static final int EOF = 0;
  public static final int LlaveApertura = 25;
  public static final int TipoDeDatos = 3;
  public static final int error = 1;
  public static final int OperadoresAtribucion = 20;
  public static final int Dolar = 34;
  public static final int ERROR = 35;
  public static final int Do = 8;
  public static final int OperadoresRelacionales = 17;
  public static final int SwitchCase = 11;
  public static final int Identificador = 31;
  public static final int Estructura = 18;
  public static final int OperadoresDeCadenas = 19;
  public static final int OperadoresMasMenos = 21;
  public static final int Numero = 33;
  public static final int ParentesisApertura = 23;
  public static final int Main = 29;
  public static final int Igual = 13;
  public static final int Comillas = 2;
}

